- src/components/header/css/component.scss
- src/components/header/html/component.hbs
Added improvement to the header component preheader. The improvement if there is no preheader logo set the pre logo text will display.
Ticket: https://squizgroup.atlassian.net/browse/QHWT-953
Repo Branch:  https://github.com/Qld-Health-Online-Team/design-system/tree/improvement/QHWT-953
> added the else statement if there is no sitelogo for the pre-header

- src/components/_global/css/forms/select/component.scss
This pull request includes a small change to the `src/components/_global/css/forms/select/component.scss` file. The change sets the width of the `select` element to 50%.
* [`src/components/_global/css/forms/select/component.scss`](diffhunk://#diff-fe25765d4ff9232e8cf13c87080720478fa244d6314444a21c2d6b556af6f9b6R306): Added `width: 50%` to the `select` element.
> Fix date field width

- src/components/a-z_listing/css/component.scss
- src/components/a-z_listing/html/component.hbs
- src/components/a-z_listing/js/manifest.json
- src/helpers/Handlebars/listAZ.js
Add Letter heading - QHWT-1106
This pull request introduces several enhancements to the A-Z listing component, including adding a new metadata field, updating the Handlebars helper, and making minor CSS adjustments. The most important changes are detailed below.
* **Addition of Metadata Field:**
- [`src/components/a-z_listing/js/manifest.json`](diffhunk://#diff-d2712a841b2729da56280a3fd1df12d155b426d0577c644440644eafb67b872cR16-R28): Added a new `letter_heading` metadata field with options for different heading levels (`h2`, `h3`, `h4`, `h5`, `span`).
* **Updates to Handlebars Helper:**
- [`src/helpers/Handlebars/listAZ.js`](diffhunk://#diff-b32c20a89216afef5d0c1180cf1d7911801e690b16d9af3946aae889782cdf8aL1-R1): Modified the `listAZ` helper function to accept a `letterHeading` parameter …
> Add Letter heading

- src/components/page_alert/css/component.scss
- src/components/page_alert/html/component.hbs
- src/components/page_alert/js/manifest.json
Rework heading - QHWT-1093
This pull request includes several changes to the `page_alert` component, focusing on improving the flexibility and styling of headings. The most important changes include adding a new `heading_level` metadata field, updating the HTML template to use this new field, and adjusting the CSS for better visual consistency.
* [`src/components/page_alert/js/manifest.json`](diffhunk://#diff-317b8955316abafe4b1af03faa02c1cd43842277855e243e28746b2b311a82c9R24-R38): Added a new `heading_level` metadata field to allow selection of heading levels (`h2` to `h6`).
* [`src/components/page_alert/html/component.hbs`](diffhunk://#diff-d317abb40b0469d96af218c59357c4d68d07527196e35c9f7605276c39c0a3e7L18-R18): Updated the template to dynamically use the selected heading level from …
> Rework heading

- src/components/horizontal_rule/html/component.hbs
Rework hr for aria QHWT-1200
This pull request includes a small change to the `src/components/horizontal_rule/html/component.hbs` file. The change adds an `aria-hidden="true"` attribute to the `<hr>` element to improve accessibility.
* [`src/components/horizontal_rule/html/component.hbs`](diffhunk://#diff-6eef2d15a4caab39c4baec081d00f862cb6109d3e00df2b253c0091b099d774fL4-R4): Added `aria-hidden="true"` attribute to the `<hr>` element to improve accessibility.
> Rework hr for aria

- src/components/accordion/css/component.scss
- src/components/accordion/html/component.hbs
Rework Accordion structure QHWT-1082
This pull request includes changes to the accordion component, focusing on updating the HTML structure and commenting out unused SCSS styles.
* [`src/components/accordion/html/component.hbs`](diffhunk://#diff-9dcbe47d05f6572c97e44505fc60eeb7ffe1e7121ac8fe47246305c3f32753f5L18-R36): Updated the accordion structure by replacing `<ul>` and `<li>` elements with `<div>` and `<h2>` elements for better semantic HTML.
* [`src/components/accordion/css/component.scss`](diffhunk://#diff-4375bae5cd43ee1e28a29a37998a6d8116c8fc4d48b8e385f1d348a988b958d2L302-R318): Commented out the `.main` class and its nested styles, which include margin adjustments for `.qld__accordion` and `.qld__accordion-group` elements.
> Rework Accordion structure

- src/components/in_page_navigation/js/global.js
Exclude Alert headings QHWT-1196
This pull request includes a change to the `src/components/in_page_navigation/js/global.js` file. The main update is to refine the selection of headings for in-page navigation by excluding specific elements.
Improvements to heading selection:
* [`src/components/in_page_navigation/js/global.js`](diffhunk://#diff-f02743a64fe8275e8a6bfa32e13070fde4d867e84d056ca3fa6cd4aebe679c8aL23-R29): Updated the `headings` variable to exclude Code CT and accordion elements (`h3`, `h4`, `h5`, `h6`) from the in-page navigation.
> Exclude Alert headings

- src/components/card_feature/html/component.hbs
Change ul li to div for feature card QHWT-1089
This pull request includes changes to the `src/components/card_feature/html/component.hbs` file to improve the structure and semantics of the HTML code and improve accessibility. The most important changes include replacing the `ul` and `li` elements with `div` elements to better align with the intended layout and usage.
HTML structure improvements:
* Replaced `ul` and `li` elements with `div` elements to enhance the semantic structure and layout of the card feature component. (`src/components/card_feature/html/component.hbs`) [[1]](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL38-R39) [[2]](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL111-R112)
> Change ul li to div for feature card

- src/components/widgets/html/component.hbs
Update Back to top href QHWT-1076
This pull request includes a small but important change to the `src/components/widgets/html/component.hbs` file. The change modifies the `href` attribute of the "Back to top" button to improve accessibility.
* [`src/components/widgets/html/component.hbs`](diffhunk://#diff-9c4e43a70c1b4ae9b35a3f900d9dcea5bd33e5f0951384cea90068cd84a61f36L3-R3): Changed the `href` attribute of the "Back to top" button from `"#"` to `"#content"` to ensure it directs users to the main content section, enhancing accessibility.
> Update Back to top href

- src/components/banner_advanced/html/component.hbs
- src/components/banner_advanced/js/manifest.json
Add accessible name - QHWT-1080
This pull request includes changes to the `banner_advanced` component to enhance accessibility by adding an ARIA label and a new metadata field. The most important changes include adding the ARIA label for icon tiles and updating the manifest to include the new metadata field.
Enhancements to accessibility:
* [`src/components/banner_advanced/html/component.hbs`](diffhunk://#diff-227eac69d05393fd7f193a70f44ec0918c3e063e3dc7227264d0965b59202e49L200-R200): Added an ARIA label to the `nav` element when `cta_icon_tiles_label` metadata is present.
Updates to metadata:
* [`src/components/banner_advanced/js/manifest.json`](diffhunk://#diff-a9887da3c6b2d89e32c4b615c1b33440b5ca8632152829fc7e1a735a6ed333bcR365-R381): Added a new metadata field `cta_icon_tiles_label` …
> Add accessible name

- src/components/tab/html/component.hbs
Add accessibility tag QHWT-1105
This pull request includes changes to improve the accessibility of the tab component in the `src/components/tab/html/component.hbs` file. The changes involve adding the `role="tab"` attribute to button elements and replacing the `<header>` element with a `<div>` element for the tab list.
Accessibility improvements:
* Added `role="tab"` attribute to each `qld__tab-button` element to enhance accessibility.
* Replaced the `<header>` element with a `<div>` element for the tab list to better align with accessibility standards.
> Add accessibility tag

- src/components/card_feature/html/component.hbs
- src/components/card_feature/js/manifest.json
- src/components/card_multi_action/html/component.hbs
- src/components/card_multi_action/js/manifest.json
- src/components/card_no_action/html/component.hbs
- src/components/card_no_action/js/manifest.json
- src/components/card_single_action/html/component.hbs
- src/components/card_single_action/js/manifest.json
- src/helpers/Handlebars/getThumbnailAlt.js
Add accessibility tags for background images QHWT-1088
This pull request includes several changes to improve accessibility by adding `aria-label` and `role="img"` attributes to various components. The most important changes include updates to the `component.hbs` files for different card types and the addition of new fields in the corresponding `manifest.json` files.
Accessibility improvements:
* [`src/components/card_feature/html/component.hbs`](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL3-R4): Added `role="img"` and `aria-label` attributes for background images and patterns, as well as for card images. [[1]](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL3-R4) …
> Add accessibility tags for background images

- src/components/basic_search/html/component.hbs
https://squizgroup.atlassian.net/browse/QHWT-1117
This pull request includes a change to the `src/components/basic_search/html/component.hbs` file to improve the accessibility of the sort functionality. The most important change is the modification of the `Sort by` label to enhance screen reader compatibility.
Accessibility improvements:
* [`src/components/basic_search/html/component.hbs`](diffhunk://#diff-cee01265c95869dbc33a81676569ee6e097921f60fcf4c86a05bf100ef277c91L114-R115): Changed the `Sort by` label to be associated directly with the `search-sort` select element by using the `for` attribute, and removed the separate `label` element with the `sr-only` class. This change ensures that screen readers can correctly identify and announce the sort functionality to users.
> label sort fix issue on new release

- src/components/pagination/css/component.scss
Update pagination colours QHWT-1213
This pull request includes several updates to the styles in the `src/components/pagination/css/component.scss` file. These changes primarily focus on improving the visual consistency and accessibility of the pagination component by updating color variables and adding new styles for different states.
Styling updates:
* Added a new color for the `:hover` and `:focus` states to improve visibility and consistency. [[1]](diffhunk://#diff-b091c9a36ecdd4e4c68fad962267094ef1a0ed7b11ab48be2738e80607f6f64cR41) [[2]](diffhunk://#diff-b091c9a36ecdd4e4c68fad962267094ef1a0ed7b11ab48be2738e80607f6f64cR50)
* Updated the color and background for `a` and `button` elements in their `:active` and `:focus` states to enhance accessibility.
* Changed the box-shadow color for …
> Update pagination colours

- src/components/data_table/css/component.scss
- src/components/data_table/js/global.js
https://squizgroup.atlassian.net/browse/QHWT-1096
This pull request includes changes to the styling and functionality of sortable table headers in the data table component. The key changes involve adding a new button style for sortable headers and updating the JavaScript to replace header text with buttons.
Styling updates:
* [`src/components/data_table/css/component.scss`](diffhunk://#diff-f587b5eefc8b68dbc016f1c4709ffb5924b9623551d5584015ecae7e0efe4d31R514-R522): Added a new class `.qld__data-table__btn` for button styles, including background, border, cursor, font-weight, and color properties.
JavaScript updates:
* [`src/components/data_table/js/global.js`](diffhunk://#diff-727762acefff5c36b2b044a1b409851cf332697206bbf29b12cc178837f4f1c4R192-R203): Updated the script to remove the …
> new branch for removing tabindex from data tables

- src/components/card_feature/html/component.hbs
Remove describedby from a tag
This pull request includes changes to the `src/components/card_feature/html/component.hbs` file to improve accessibility and simplify the code. The most important changes are:
Accessibility improvements:
* Removed unnecessary `aria-describedby` attributes from the anchor tags to streamline the HTML and ensure better accessibility. [[1]](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL46-R46) [[2]](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL58-R58)
> Remove describedby from a tag

- src/components/_global/css/tags/component.scss
- src/html/component-tag_list.html
Update structure and styles for tags
This pull request includes changes to the styling and structure of the tag components in the SCSS and HTML files to improve the layout and accessibility.
* Added new styles for the `qld__tag-list--wrapper` and `qld__tag-list--title` classes to improve the layout and alignment of tag lists.
* Updated the `qld__tag--filter-close` class to include new styles for focus state and improved accessibility.
* Modified the `qld__tag--filter-close-icon` class to adjust the margin and background color. [[1]](diffhunk://#diff-1afa2de127670e3587fb10b831556ef10b72352e6927a9cc9ac5883de70db696L210-L231) [[2]](diffhunk://#diff-1afa2de127670e3587fb10b831556ef10b72352e6927a9cc9ac5883de70db696L274-R319)
* Wrapped the applied filter tags in a new `qld__tag-list--wrapper` …
> Update structure and styles for tags

- src/components/_global/js/forms/global.js
- src/html/component-forms.html
Make Hint Text Accessible in Form Fields
This pull request includes several changes to the `src/components/_global/js/forms/global.js` file and a minor change to the `src/html/component-forms.html` file. The changes focus on adding new functionality for form validation and accessibility improvements.
* Added a new function `linkHintText` to associate hint text with form fields using `aria-describedby` for better accessibility.
* Modified the form initialization to call the `linkHintText` function for each form.
* Updated the class of a `div` element to `qld__body qld__form` for better styling consistency.
> Make Hint Text Accessible in Form Fields

- src/components/_global/css/btn/component.scss
Fix Tertiary Button Styles
This pull request includes changes to the `src/components/_global/css/btn/component.scss` file to update the styles for tertiary buttons. The most important changes involve modifying the underline styles and adding active state styles for these buttons.
Updates to underline styles:
* Changed the underline style from 'noUnderline' to 'underline' for light and dark themes in the `QLD-underline` mixin. [[1]](diffhunk://#diff-4acd20f5da81e2b8806110afb65bd74cd378ad15385a297ebd5e1e08a75d103cL321-R321) [[2]](diffhunk://#diff-4acd20f5da81e2b8806110afb65bd74cd378ad15385a297ebd5e1e08a75d103cL384-R394)
Additions to active state styles:
* Added active state styles for tertiary buttons, setting the background color, border color, text color, and text decoration. …
> Fix Tertiary Button Styles

- src/styles/global.scss
Adjust email text to fit within the container
This pull request includes a small change to the `src/styles/global.scss` file. The change adds a new style rule to handle email links by breaking long words to improve readability.
Styling update:
* [`src/styles/global.scss`](diffhunk://#diff-2c0189636ff225dd87da97bcea9b585e70a25a5f601b816456f20bf146bec8adR99-R103): Added a new CSS rule to apply `overflow-wrap: break-word;` to email links (`a[href^="mailto:"]`).
> Break email text to fit container

- src/components/updated_date/html/component.hbs
- src/components/widgets/css/component.scss
https://squizgroup.atlassian.net/browse/QHWT-1272
This pull request includes changes to the `src/components/updated_date/html/component.hbs` and `src/components/widgets/css/component.scss` files to update the source of SVG icons used in the back to top (updated date) component.
Updates to SVG icon references:
- [src/components/updated_date/html/component.hbs](https://github.com/Qld-Health-Online-Team/design-system/commit/0759eadfcad9800606c71dea2bcdb54eec08f913#diff-ad8ba1636509c5d4006e17a1c54eb21c9f6546a8f30a77bda0a6f46ad431212e): Added in-line svg elements to use the arrow-up icon. The `use` element within references `coreSiteIcons`
Updates to stylesheet:
- [src/components/widgets/css/component.scss](https://github.com/Qld-Health-Online-Team/design-system/commit/0759eadfcad9800606c71dea2 …
> QHWT-1272 | Back to top | Update svg icons and styling

- src/components/header/html/component.hbs
https://squizgroup.atlassian.net/browse/QHWT-1276
This pull request includes changes to the `src/components/header/html/component.hbs` file to update the source of SVG icons used in the header component. 
Updates to SVG icon references:
- [src/components/header/html/component.hbs](https://github.com/Qld-Health-Online-Team/design-system/commit/d4ddc149bddb6f45ab97a3785da6b0b1526db6f6#diff-0fefeb5a96968b15037fcee3b4d70d411f4725e63317fbf0dbdddde72e4b30bc): Changed the use element references for search, close, and menu icons to use coreSiteIcons instead of siteDefaultIcons
Testing sites:
- https://qhonline.com.au/qgds-development/component-core
- https://www.designsystem.qld.gov.au/
Testing instructions:
- Compare icon changes, and that the url path to the svgs are updated
- Check …
> QHWT-1276 | Header | Update svg icons

- src/components/global_alert/css/component.scss
- src/components/global_alert/html/component.hbs
- src/styles/imports/variables.scss
https://squizgroup.atlassian.net/browse/QHWT-1292
https://squizgroup.atlassian.net/browse/QHWT-1271
This pull request includes changes to `src/components/global_alert/css/component.scss`, `src/components/global_alert/html/component.hbs`, and `src/styles/imports/variables.scss`. This was to update the svg icons, and fix the font issues within the global alert component.
Updates to stylesheet:
- [src/components/global_alert/css/component.scss](https://github.com/Qld-Health-Online-Team/design-system/commit/3e3317c6e4093c8ac1f7736232242fef777a706f)
- Refactor font size to not only use the global font-size variable, but also standardize them all to 14px
- Fix the top and bottom margins for the alerts, changing on screen size
- Update font-weight to be 600 (from 700)
- Refactor the styling for …
> QHWT-1292 | Global alert | Update svg icons and fix font issues

- src/components/card_feature/css/component.scss
https://squizgroup.atlassian.net/browse/QHWT-1133
This pull request includes updates to the CSS for card components, specifically focusing on the hover states and visited link styles for both light and dark themes.
Styling updates for card components:
* Added hover styles for tags in light-themed cards, including background color, text color, and border color changes.
* Introduced new default styles for visited links in light-themed cards.
* Added hover styles for visited links in light-themed cards, ensuring consistency with hover styles for non-visited links.
* Defined hover styles for visited links in dark-themed cards, including color and background color adjustments.
> added new color styles tags cards

- src/components/_global/css/tabs/component.scss
- src/components/tab/css/component.scss
- src/components/tab/html/component.hbs
This pull request includes significant changes to the CSS and HTML for tab components, focusing on cleaning up the code and improving the styling of tab navigation buttons. The most important changes include removing redundant and commented-out CSS code, updating the styling for tab navigation buttons, and switching from FontAwesome icons to SVG icons.
Codebase cleanup and simplification:
* [`src/components/_global/css/tabs/component.scss`](diffhunk://#diff-3d4b5f9e560124fce99d13c8c8f0d84a7d7727295987c96b3ec47d0fdebcd661L39-L42): Removed an empty CSS rule for `.qld__tab + .qld__tab`.
* [`src/components/tab/css/component.scss`](diffhunk://#diff-b4dae899d8ac05179fab482cd1f73c64e7a733dd3211385ce3abf21a54b39722L133-R143): Removed multiple instances of redundant and commented-out CSS code. …
> QHWT-1296 | Tabs | Update svg icons

- src/components/basic_search/html/component.hbs
- src/components/pagination/html/component.hbs
- src/components/pagination/js/manifest.json
- src/html/component-pagination.html
This pull request updates the pagination components to use a new icon set and improves the structure of the pagination manifest. The most significant changes include replacing hardcoded SVG paths with references to a centralized icon library, ensuring consistency and maintainability, and restructuring the `manifest.json` file for better readability and alignment with the updated pagination logic.
* Replaced hardcoded SVG paths with `<use>` references to the centralized `coreSiteIcons` library for the "ellipsis," "arrow-left," and "arrow-right" icons in `src/components/basic_search/html/component.hbs`.
* Updated `src/components/pagination/html/component.hbs` to use the `coreSiteIcons` library instead of the `siteDefaultIcons` library for the same icons, ensuring consistency across …
> QHWT-1285 | Pagination | Update svg icons

- src/styles/imports/utilities.scss
This pull request introduces a new utility class for styling multi-column text layouts in the `src/styles/imports/utilities.scss` file. The changes aim to improve text formatting and ensure better readability across different screen sizes.
* Added `.qld__text-columns-2` class to enable a two-column layout for text on screens wider than 992px. It includes a `column-gap` of `2rem` for spacing between columns.
* Ensured that headings (`h1` through `h6`) within `.qld__text-columns-2` do not break across columns by using `break-after: avoid`, `break-inside: avoid`, and `page-break-after: avoid`.
* Introduced `.qld__keep-together` utility class to keep block-level content within a single column by applying `break-inside: avoid`, `display: inline-block`, and `width: 100%`.
> QHWT-1325 | New text-columns-2 utility class.

- src/components/promo_panel/css/component.scss
This pull request makes a small improvement to the styling in the `src/components/promo_panel/css/component.scss` file. The change updates the CSS selector for the `h2.qld__display-xl` element to apply styles only when it is preceded by an element with the class `qld__promo-panel__container-icon`.
> fix/QHWT-1296-QHWT-1326 | Promo icon + title spacing

- src/components/footer/css/component.scss
This pull request includes updates to the `src/components/footer/css/component.scss` file to adjust the layout and styling of the footer's link lists. The changes focus on improving responsiveness and simplifying the CSS structure.
* Updated the `ul.qld__link-list` to use a column layout by default (`flex-direction: column`) and switch back to a row layout for smaller screens using a media query (`QLD-media(lg, "down")`). This improves the footer's adaptability to different screen sizes.
* Removed redundant `flex-basis` properties for list items, relying on the `width` property for layout control instead.
* Removed the `align-items: end` property from the `ul.qld__link-list`, simplifying the alignment rules.
> QHWT-1352 | Footer | Modify css to ensure footer link cols have proper directions

- src/components/breadcrumbs/css/component.scss
This pull request makes responsive design improvements to the breadcrumb component's styling by adding media query mixins to adjust the positioning for smaller screen sizes.
Responsive design changes:
* [`src/components/breadcrumbs/css/component.scss`](diffhunk://#diff-c9fc5116312e9a8de14f60fb23058d8b41d5027ccc6439ec1d67ca1e25ae1929R253-R255): Added a `QLD-media` mixin to the `.qld__breadcrumbs__item` class to adjust the `left` property for screens `lg` size and smaller.
* [`src/components/breadcrumbs/css/component.scss`](diffhunk://#diff-c9fc5116312e9a8de14f60fb23058d8b41d5027ccc6439ec1d67ca1e25ae1929R276-R279): Added a `QLD-media` mixin to the `.qld__overflow_menu--breadcrumbs` class to adjust the `left` property for screens `lg` size and smaller.
> QHWT-1351 | Breadcrumbs | Add media query to only indent breadcrumbs only on mobile

- src/components/video_player/css/component.scss
- src/components/video_player/html/component.hbs
- src/components/video_player/js/manifest.json
This pull request refactors the `video_player` component by improving its CSS structure, introducing new alignment options for layouts, and updating metadata configuration. The main changes focus on enhancing maintainability and flexibility in styling and layout customization.
* Reformatted CSS properties for better readability by breaking long property values into multiple lines. This affects various selectors, including `.qld__video__player--summary` and `.qld__accordion__body-wrapper`. [[1]](diffhunk://#diff-379d678e7f90a26f7de6bfabd06e424e4d28041c852aab1efd12ff2cb6420f97L7-R8) [[2]](diffhunk://#diff-379d678e7f90a26f7de6bfabd06e424e4d28041c852aab1efd12ff2cb6420f97L26-R38) [[3]](diffhunk://#diff-379d678e7f90a26f7de6bfabd06e424e4d28041c852aab1efd12ff2cb6420f97L51-R61) …
> Add video item alignment

- src/components/basic_search/html/component.hbs
This pull request makes a small but meaningful change to the `src/components/basic_search/html/component.hbs` file. The change adds an `id` attribute with the value `content` to the `<section>` element.
> fix/QHWT-1328-QHWT-1274: Content id for search page - Back to top

- src/components/horizontal_rule/css/component.scss
- src/html/component-horizontal_rule.html
This pull request introduces enhancements to the styling and accessibility of horizontal rules in the Queensland Design System, as well as a new HTML template for the `horizontal_rule` component. The changes improve visual consistency across themes and provide accessible and decorative variations for different body sections.
* Added accessible and decorative versions of the `qld__horizontal-rule` class for different body themes (e.g., light, dark, alt) with appropriate background colors. These styles ensure better visual contrast and accessibility. (`src/components/horizontal_rule/css/component.scss`)
* Introduced a new `horizontal_rule` HTML template that demonstrates the usage of accessible and decorative horizontal rules across various themes. This includes examples for different sizes …
> QHWT-1324 | Horizontal rule | Add colours to horizontal rule for accessible body elements

- src/components/basic_search/css/component.scss
This pull request focuses on improving code readability and consistency in the `src/components/basic_search/css/component.scss` file. The changes include standardizing numerical formatting, fixing syntax issues, and removing unnecessary whitespace.
* Updated all fractional units to use a leading zero for consistency (e.g., `.5unit` → `0.5unit`, `.875unit` → `0.875unit`). [[1]](diffhunk://#diff-0e2b8209daffef9544b4f52b1f0e1ba14b8a8e17f8dbd9cccd4a644b317fcc4aL33-R34) [[2]](diffhunk://#diff-0e2b8209daffef9544b4f52b1f0e1ba14b8a8e17f8dbd9cccd4a644b317fcc4aL67-R70) [[3]](diffhunk://#diff-0e2b8209daffef9544b4f52b1f0e1ba14b8a8e17f8dbd9cccd4a644b317fcc4aL96-L108) [[4]](diffhunk://#diff-0e2b8209daffef9544b4f52b1f0e1ba14b8a8e17f8dbd9cccd4a644b317fcc4aL134-R131) …
> Update select styling on basic search.

- src/components/_global/css/forms/select/component.scss
This pull request makes a small change to the `src/components/_global/css/forms/select/component.scss` file. It replaces the `select` selector with `.qld__select` to likely improve specificity or align with a naming convention.
> Update datetime select box styling.

- src/components/main_navigation/css/component.scss
- src/components/mega_main_navigation/css/component.scss
[QHWT-1311](https://squizgroup.atlassian.net/browse/QHWT-1311)
This pull request updates the styling for navigation components in the `src/components/main_navigation/css/component.scss` and `src/components/mega_main_navigation/css/component.scss` files. The changes primarily focus on improving hover states and adjusting border and background colors for better visual consistency.
* Updated the hover state for active navigation items to use `var(--QLD-color-dark__action--primary-hover)` for border color.
* Adjusted hover background and border colors to `var(--QLD-color-dark__background--alt)` and `var(--QLD-color-dark__action--primary-hover)`, respectively, for improved visual hierarchy.
* Changed the border color for large screen sizes to `var(--QLD-color-dark__background--shade)` for …
> fix/QHWT-1357-1311: Bug: Dark main nav active and hover colours are incorrect

- src/components/card_multi_action/css/component.scss
- src/components/card_no_action/css/component.scss
[QHWT-1318](https://squizgroup.atlassian.net/browse/QHWT-1318)
This pull request introduces accessibility improvements and minor styling adjustments to the `card_multi_action` and `card_no_action` components by refining focus states and hover behaviors. The changes ensure better visual feedback for users interacting with links and buttons.
* Added focus outlines for `a.qld__card--clickable__link` and `a.qld__card__footer-link` in `card_multi_action` to enhance keyboard navigation visibility.
* Commented out the removal of focus outlines in `card_no_action` to preserve accessibility for focused elements. [[1]](diffhunk://#diff-65ad3987205948c7aacc1b41d7993936fc3aac721901a4ac6ab05db0506bc01cR380-R387) [[2]](diffhunk://#diff-65ad3987205948c7aacc1b41d7993936fc3aac721901a4ac6ab05db0506bc01cL398 …
> fix/QHWT-1357-1318: Multi action cards have incorrect and missing focus colours in various scenarios

- src/components/_global/css/forms/control_inputs/component.scss
- src/components/_global/css/tags/component.scss
- src/components/_global/css/toggle_and_tool_tip/component.scss
- src/components/main_navigation/css/component.scss
- src/components/mega_main_navigation/css/component.scss
- src/styles/imports/mixins.scss
This pull request introduces several updates to the SCSS files, focusing on enhancing the flexibility of mixins, improving accessibility styles, and standardizing code formatting. The most significant changes include updates to the `QLD-outline` and `QLD-focus` mixins to support additional parameters, accessibility improvements across multiple components, and consistent use of double quotes in SCSS files for better readability.
* Updated the `QLD-outline` mixin to include a new `$rounded` parameter, allowing control over border-radius application. The `QLD-focus` mixin was also updated to pass the `$rounded` parameter to `QLD-outline` for improved flexibility (`src/styles/imports/mixins.scss`).
* Refactored the `QLD-media`, `QLD-fontgrid`, `QLD-container-padding`, `QLD-container-margin`, …
> QHWT-1323 | Outline mixin | Update focus outline border radius

- src/components/widgets/css/component.scss
This pull request introduces a new mixin and updates the styles for the "Back to Top" widget in both light and dark themes to improve hover, focus, and active state visuals.
* Added a new SCSS mixin `QLD-BTT-arrow-colours` to handle the arrow color changes on hover, focus, and active states for the "Back to Top" widget.
* Updated `.qld__widgets__back_to_top` styles for light and dark themes to ensure visited links have appropriate colors and underline styles, and applied the new mixin for consistent interaction feedback.
> QHWT-1397 | Back to top | Fix interactive and visited colours

- src/components/footer/css/component.scss
- src/components/footer/html/component.hbs
- src/data/site.json
This pull request updates how contact icons are rendered in the footer component, switching from font-based icons to SVG icons for improved accessibility and consistency. The changes also set the default contact icon to "email" in the site metadata.
**Footer contact icon rendering:**
* Replaced font-based icon markup with conditional SVG rendering for "phone" and "email" icons in `component.hbs`, using core site icons for improved accessibility and visual consistency.
**Styling updates:**
* Updated the CSS selector and styling in `component.scss` to target SVG icons (`svg.qld__icon`) instead of the previous font icon class, adjusting size and removing unnecessary styles.
**Configuration update:**
* Set the default value of `footerCTAContactIcon` to "email" in `site.json`, ensuring the …
>  QHWT-1358 | Footer | Update fa icons

- src/components/banner_advanced/html/component.hbs
- src/components/card_feature/html/component.hbs
- src/components/card_multi_action/html/component.hbs
- src/components/card_single_action/css/component.scss
- src/components/card_single_action/html/component.hbs
- src/components/page_alert/css/component.scss
- src/html/component-card_feature.html
- src/html/component-card_single_action.html
This pull request refactors how arrow icons are rendered across several card components, replacing CSS-based masked icons with inline SVGs for improved consistency and maintainability. It also cleans up and standardizes some CSS formatting, particularly in the `page_alert` component, removing unused code and ensuring consistent use of quotes and spacing.
* Replaced the `.qld__card__arrow` div and CSS mask-based arrow icon with an inline SVG (`<svg>`) for the arrow in `banner_advanced`, `card_feature`, `card_multi_action`, and `card_single_action` components, improving icon consistency and maintainability.
* Updated the `.qld__card--arrow-icon` CSS class to style the inline SVG arrow, removing mask-image logic and ensuring proper hover and dark mode color transitions.
* Standardized the …
> QHWT-1424 | Cards | Update card arrows

- src/components/main_navigation/css/component.scss
- src/components/mega_main_navigation/css/component.scss
This pull request updates the SCSS styles for both the `main_navigation` and `mega_main_navigation` components, focusing on improving visual consistency and clarity for navigation item states (such as "open", "active", and "hover") across different themes (light and dark). The changes primarily refine how navigation links and items are styled when they are active or hovered, ensuring they use the correct color variables and border styles.
**Navigation styling improvements:**
* Refined the styling for open navigation links in `main_navigation` by removing redundant selectors and consolidating color assignments, so open links now consistently use the correct heading color for both light and dark themes.
* Updated the hover state for navigation items in `mega_main_navigation` to use the dark …
> QHWT-1406 | Mega and main nav | Fix menu hover styling

- src/components/header/css/component.scss
- src/components/main_navigation/css/component.scss
- src/components/main_navigation/js/global.js
- src/components/mega_main_navigation/css/component.scss
- src/components/mega_main_navigation/js/global.js
- src/styles/imports/mixins.scss
This pull request focuses on improving accessibility and consistency of focus styles across navigation components, as well as refining the mobile navigation experience. The main changes include enhanced focus styling for both light and dark modes, mobile-specific style adjustments, and code clean-up and consistency improvements in the JavaScript handling navigation behavior.
* Added and updated `QLD-focus` mixins with explicit mode and offset parameters for header and main navigation components, ensuring consistent focus ring appearance in both light and dark themes. 
* Introduced dark mode-specific focus outline colors for navigation elements, improving accessibility for users in dark theme.
* Reset the right padding on navigation list items for mobile view to prevent layout issues where …
> QHWT-1407 | Mega main nav | Fix colour issues with focus
