Qld-Health-Online-Team/design-system

package-lock.json, src/components/breadcrumbs/html/component.hbs, src/data/current.json
This will cause folders not to show in the breadcrumbs
=> Added asset_type_code check for breadcrumbs items 

package-lock.json
Build of the master with the latest changes 
the goal is to have qhwt-693 fixes in prod.
=> Building for production - qhwt-693

src/components/_global/css/forms/select/component.scss
Adding the missing comment for select box hotfix
=> Fixing it for the select as we ll

src/components/data_table/js/global.js
Fixed the data table not showing some rows - wts-646
=> Table not showing some rows bug fixed - WTS-646

src/components/card_no_action/html/component.hbs
Needed to add card_ to the background so the card background color will change
=> fix the metadata for the card background color

src/components/card_no_action/js/manifest.json
Fixed the dark alternate class
=> fixed the Dark alternate class

src/components/_global/css/banner_contained/component.scss
Updated the styling for the body breadcrumbs when the contained banner is actived
=> added the styling for the body breadcrumbs

src/components/_global/css/banner_contained/component.scss
added margin to the top of the tab section when the contained banner is activated
=> added the margin for the tab content page

src/components/_global/css/banner_contained/component.scss
added the border shadow for the breadcrumbs
=> updated the breadcrumbs border shadow

src/components/_global/css/banner_contained/component.scss
fix the border for the breadcrumbs
=> fix the the border for the breadcrumbs

src/components/_global/css/banner_contained/component.scss
=> fixing style for contained banner so it's not using id's

src/components/_global/css/banner_contained/component.scss
fix styling for the body for contained banner
=> fix styling for the body for contained banner

src/components/_global/css/banner_contained/component.scss
adjust the body padding for when the contained banner is no showing
=> adjust the body padding for when the contained banner is no showing

src/components/_global/css/banner_contained/component.scss
testing a override body style for contained banner
=> testing a override body style for contained banner

src/components/_global/css/banner_contained/component.scss
fixed the styling for the contained banner with no breadcrumbs or banner
=> fixed the styling for the contained banner with no breadcrumbs or banner

src/components/_global/css/banner_contained/component.scss
Styling for the contained banner
Support Ticket: https://squizgroup.atlassian.net/browse/QHWT-854
=> added styling for the contained banner

src/components/card_multi_action/html/component.hbs, src/components/card_no_action/html/component.hbs, src/components/card_single_action/html/component.hbs
Updated the aria-label for 3 of the card components
=> updated the aria-label

src/components/card_feature/html/component.hbs, src/components/card_multi_action/html/component.hbs, src/components/card_no_action/html/component.hbs, src/components/card_single_action/html/component.hbs
Added the aria-label to the following components 
- Cards No Action
- Card Feature
- Card multi-action
- Card single action
Jira Ticket: https://squizgroup.atlassian.net/browse/QHWT-858
=> added the aria-label to the cards image

src/components/_global/css/body/component.scss
=> Fixing the spacings - QHWT-876

src/components/card_feature/html/component.hbs, src/components/card_multi_action/html/component.hbs, src/components/card_no_action/html/component.hbs, src/components/card_single_action/html/component.hbs
updated the aria-labels for the alt text
=> updated the aria-labels for the alt text

src/components/card_feature/html/component.hbs, src/components/card_multi_action/html/component.hbs, src/components/card_no_action/html/component.hbs, src/components/card_single_action/html/component.hbs
=> testing the aria-labels

src/components/card_feature/html/component.hbs, src/components/card_single_action/html/component.hbs
=> updated the aria labels

src/components/card_feature/html/component.hbs
fixed the aria-label for the card feature to use alt text if available
=> fixed the aria-label for the card feature to use alt text if available

src/components/card_multi_action/html/component.hbs
fixed the aria-label for the single action  to use alt text if available
=> fixed the aria-label for the single action  to use alt text if available

src/components/file_upload/css/component.scss
Sorry - small fix for the styling.
Was a clash of colours when the component had an error & was updating/uploading.
=> Small colour fix for error class

package.json, src/components/file_upload/js/global.js
removing the es6 
updating the app version to 1.4.2 (matching with the release version)
=> Release 1.4.2

src/components/file_upload/js/global.js
=> Removed optional chaining from JS

src/components/basic_search/css/component.scss, src/components/file_upload/css/component.scss, src/components/mega_main_navigation/css/component.scss
https://squizgroup.atlassian.net/browse/QHWT-990
=> design token - fixing wrong variables

src/components/accordion/html/component.hbs, src/components/accordion/js/global.js
=> Add aria-expanded attribute

src/components/file_upload/js/global.js
Rework xss for file upload QHWT-1180
This pull request includes several changes to the file upload functionality in `src/components/file_upload/js/global.js`. The main improvements focus on enhancing file name validation, sanitizing file names, and improving error handling.
* Introduced a new regex pattern to check for illegal characters and HTML/JS patterns in file names.
* Added a new function `sanitiseAndValidateFileName` to sanitize file names by removing potentially dangerous and unwanted characters.
* Improved error messages for unsupported characters in file names and empty file uploads.
* Refactored the file handling loop to use `for...of` and created new `File` objects with sanitized file names while preserving original file properties.
* Minor code cleanup and formatting …
=> Rework xss for file upload

src/components/footer/html/component.hbs
=> Updating heading

src/components/accordion/html/component.hbs, src/components/accordion/js/manifest.json
Make accordion heading dynamic
=> Make accordion heading dynamic

src/components/data_table/css/component.scss, src/components/data_table/js/global.js, src/components/pagination/css/component.scss
Change li to button for dataTable pagination QHWT-1097
This pull request includes several changes to improve the accessibility and functionality of the pagination and data table components. The most important changes include converting pagination links to buttons, updating CSS styles to support the new button elements, and ensuring proper focus outlines for accessibility.
Changes to pagination and data table components:
* [`src/components/data_table/js/global.js`](diffhunk://#diff-727762acefff5c36b2b044a1b409851cf332697206bbf29b12cc178837f4f1c4L112-R123): Converted pagination links (`<a>`) to buttons (`<button>`) for better accessibility and added logic to handle the new button elements. Removed `role="link"` and `tabindex="0"` attributes from pagination list items. …
=> Change li to button for dataTable pagination

src/components/card_multi_action/html/component.hbs
=> Fix container

src/components/page_alert/css/component.scss, src/components/page_alert/html/component.hbs, src/components/page_alert/js/manifest.json, src/html/component-forms.html
The Page Alert component has been updated to include an SVG within the HTML while still supporting the pseudo-icon.
=> Page Alert Icon Changed to SVG

src/components/card_feature/css/component.scss, src/components/card_feature/html/component.hbs, src/components/card_multi_action/css/component.scss
Remove a tag from Feature card and restyle
=> Rework on card feature

src/components/tab/css/component.scss, src/components/tab/js/global.js
Update tab focus style and fix the key navigation order
=> Update tab focus

src/components/updated_date/css/component.scss, src/components/updated_date/html/component.hbs
https://squizgroup.atlassian.net/browse/QHWT-1081
=> changed qld__widgets class to be more specific qld__widgets__back_to_top

src/components/breadcrumbs/js/global.js
Rewrite in a traditional JS
This pull request includes changes to improve the readability and robustness of the breadcrumb component in `src/components/breadcrumbs/js/global.js`. The most important changes include the removal of optional chaining, the addition of null checks, and the formatting of code for better readability.
Improvements to readability and robustness:
* Removed optional chaining from the `bannerBreadCrumb` parent element check to ensure compatibility with environments that do not support optional chaining.
* Added a null check for `containerFluid` to handle cases where the element might not exist, preventing potential runtime errors.
* Formatted the calculation of `contentPaddings` and `paddings` to improve code readability and maintainability.
=> breadcrumbs overflow fix

src/components/data_table/js/global.js
=> Update Data Table TH

src/components/_global/css/forms/text/component.scss, src/styles/imports/utilities.scss
Modify the CSS to allow the use of custom classes for enhanced flexibility and customisation.
=> Update CSS to Support Custom Classes

src/components/banner/html/component.hbs, src/components/banner_advanced/html/component.hbs, src/components/banner_advanced/js/manifest.json, src/components/banner_basic/html/component.hbs, src/components/banner_intermediate/html/component.hbs, src/components/banner_intermediate/js/manifest.json, src/components/basic_search/html/component.hbs, src/components/breadcrumbs/css/component.scss, src/components/breadcrumbs/html/component.hbs
Update Breadcrumb Display for Tablet Screens
This pull request introduces new functionality to display breadcrumbs for tablet devices across multiple banner components and updates placeholder image URLs in manifest files.
Breadcrumbs for tablet devices:
* [`src/components/banner/html/component.hbs`](diffhunk://#diff-f3877ca46c34d84386c7d6d0b1b71a6df2850c121d65b27d8b643093a53af103R38-R60): Added breadcrumbs display logic for tablet devices.
* [`src/components/banner_advanced/html/component.hbs`](diffhunk://#diff-227eac69d05393fd7f193a70f44ec0918c3e063e3dc7227264d0965b59202e49R107-R133): Added breadcrumbs display logic for tablet devices.
* [`src/components/banner_basic/html/component.hbs`](diffhunk://#diff-2c3deb69454745b7bed3f74e338d482e0d74f01f3a4919bc571e9ee915f894f7L100-R122): Added …
=> Update Breadcrumb Display for Tablet Screens

src/components/a-z_listing/html/component.hbs
Rebuilding and running workflow for PR #220
=> Add space for testing

package.json
Rebuild for release 1.11.0 #220
=> Update core version to 1.11.1

package.json
=> Update core version to v1.11.2

package.json
=> Update core version to v1.11.3

src/components/_global/css/forms/text/component.scss
This pull request includes changes to the `src/components/_global/css/forms/text/component.scss` file to improve the organization and readability of the CSS rules for text input elements.
CSS improvements:
* Removed redundant selectors for `.sq-form-question-email-address input` and `.qld__text-input, select, .qld__select` to streamline the CSS rules.
* Reformatted the remaining selectors for better readability and maintenance.
=> Rework Email field resizing

src/components/mega_main_navigation/css/component.scss, src/components/video_player/css/component.scss, src/components/video_player/html/component.hbs, src/components/video_player/js/global.js, src/components/video_player/js/manifest.json, src/data/current.json, src/html/component-video_player.html
This pull request includes several changes to the styling and functionality of the video player component. The most important changes include updates to the CSS for better alignment and visual consistency, new HTML structure for embedding videos, and JavaScript for handling accordion behavior.
* [`src/components/mega_main_navigation/css/component.scss`](diffhunk://#diff-a544d0b400495f5d9812f92061b653e53150492e49ff5dd146c8569f1529d61fL110-R106): Adjusted padding values for better alignment in larger screens.
* [`src/components/video_player/css/component.scss`](diffhunk://#diff-379d678e7f90a26f7de6bfabd06e424e4d28041c852aab1efd12ff2cb6420f97R1-R220): Added new styles for various video player elements, including captions, transcripts, and different background themes.
* …
=> Release v1.12.0

src/components/promo_panel/css/component.scss
https://squizgroup.atlassian.net/browse/QHWT-1069
Changes made:
- Add clamped paddings on xl screen sizes, > 1312px
- References figma designs at https://www.figma.com/design/qB3lhnEs7c5pOP7pGtDhdY/Clamp-spacing?node-id=0-1&p=f&t=u0haAlwhsk3LNUw0-0
This pull request focuses on cleaning up and optimizing the SCSS for the promo panel component. The main changes involve removing unnecessary whitespace and refactoring background and padding properties for better consistency and maintainability.
* Removed unnecessary whitespace throughout the `component.scss` file. [[1]](diffhunk://#diff-f80e0d0e83e3876505d5dae3a4f24934639206837a81a33f33634061c7a1ee42L6) [[2]](diffhunk://#diff-f80e0d0e83e3876505d5dae3a4f24934639206837a81a33f33634061c7a1ee42L219-L224) …
=> QHWT-1069 | Promo panel | Update padding values for xl screen size

src/components/a-z_listing/js/global.js
https://squizgroup.atlassian.net/browse/QHWT-917
This pull request includes improvements to the scrolling functionality in the `src/components/a-z_listing/js/global.js` file. The changes ensure that the page only attempts to scroll if the target element exists.
Enhancements to scrolling functionality:
* Added a check to ensure the element exists before animating the scroll to the target element in the `hash` section.
* Added a check to ensure the element exists before animating the scroll to the target element in the `target` section.
=> added conditional check before csalling animate function

src/components/_global/css/body/component.scss
This pull request focuses on improving the readability, consistency, and maintainability of the SCSS code in the `src/components/_global/css/body/component.scss` file. The changes include formatting adjustments, style consistency updates, and minor code improvements.
* Removed unnecessary blank lines and trailing whitespace to improve code readability. [[1]](diffhunk://#diff-8ab83162242766341b05f7754106ec5d8b9507bb43e806ede37bf22385c04500L150) [[2]](diffhunk://#diff-8ab83162242766341b05f7754106ec5d8b9507bb43e806ede37bf22385c04500L169) [[3]](diffhunk://#diff-8ab83162242766341b05f7754106ec5d8b9507bb43e806ede37bf22385c04500L204) [[4]](diffhunk://#diff-8ab83162242766341b05f7754106ec5d8b9507bb43e806ede37bf22385c04500L218) [[5]](diffhunk://#diff-8ab83162242766341b05f7754106ec5d8b9507bb43e806ede3 …
=> QHWT-1287 | Global links | Remove hover styles for links on dark themes.

src/components/_global/css/btn/component.scss, src/components/_global/css/link_list/component.scss, src/html/component-btn.html, src/html/component-global-elements.html
This pull request refactors the `src/components/_global/css/btn/component.scss` file to improve maintainability and consistency by replacing `i` selectors with `.qld__icon` and standardizing spacing and syntax. Below are the key changes grouped by theme:
* Replaced all instances of `i` selectors with `.qld__icon` for better semantic clarity and maintainability. This change affects various button states, including hover, focus, and disabled states. [[1]](diffhunk://#diff-4acd20f5da81e2b8806110afb65bd74cd378ad15385a297ebd5e1e08a75d103cL55-R56) [[2]](diffhunk://#diff-4acd20f5da81e2b8806110afb65bd74cd378ad15385a297ebd5e1e08a75d103cL103-L105) [[3]](diffhunk://#diff-4acd20f5da81e2b8806110afb65bd74cd378ad15385a297ebd5e1e08a75d103cL166-R181) …
=> QHWT-1345 | Buttons | Update icons for button component

src/components/tab/js/global.js
This pull request introduces several changes to the `src/components/tab/js/global.js` file, focusing on improving code readability, adding new functionality, and fixing potential issues with tab navigation and scrolling. Key updates include the addition of new helper functions, improved handling of special characters in selectors, and enhanced event handling for better user experience.
* Replaced single quotes with double quotes for consistency in the `"use strict"` directive.
* Reformatted long lines of code for better readability, such as in the `scrollRight` function and various event listeners. [[1]](diffhunk://#diff-6f879a6a56ce9a3b2c11f9e803fbb296ce7597fc7df90f374b0a66e75c5736d3L39-R43) [[2]](diffhunk://#diff-6f879a6a56ce9a3b2c11f9e803fbb296ce7597fc7df90f374b0a66e75c5736d3L180-R273) …
=> Fix in Page Nav issue within Tab component

src/components/updated_date/css/component.scss, src/components/updated_date/html/component.hbs
This pull request includes updates to the `updated_date` component in both its SCSS and HTML files to improve styling and accessibility. The key changes involve modifying layout styles and replacing the "Back to top" button with a simplified link structure.
=> Back to top

src/components/multi_column/css/component.scss, src/components/multi_column/html/component.hbs, src/components/multi_column/js/manifest.json, src/styles/imports/utilities.scss
[https://squizgroup.atlassian.net/browse/QHWT-1327](QHWT-1327)
This pull request introduces enhancements to the spacing utilities and multi-column component in the codebase. It adds new spacing classes, updates existing ones to improve specificity, and integrates a new metadata field to control row spacing dynamically. These changes aim to provide more flexibility and consistency in spacing across components.
* Updated existing spacing utility classes in `src/styles/imports/utilities.scss` to include more specific selectors for better control, such as `* + .qld__margin-t-section` and similar updates for other spacing classes. [[1]](diffhunk://#diff-4d1ca54ad5b0eb6ecc661f483f2d4b76044d41aea614174f905e219d07357aaaL350-R350) [[2]](diffhunk://#diff-4d1ca54ad5b0eb6ecc661f483f2d4b76044d41aea6141 …
=> QHWT-1327:  Bug: Multi-col component spacing bugs

.storybook/globals.js, src/components/_global/css/direction_links/component.scss, src/stories/DirectionLinks/DirectionLinks.js, src/stories/DirectionLinks/DirectionLinks.mdx, src/stories/DirectionLinks/DirectionLinks.stories.js, src/stories/SelectBox/SelectBox.js, src/stories/SelectBox/SelectBox.mdx, src/stories/SelectBox/SelectBox.stories.js
This pull request introduces new features for direction links and updates the select box component to support multiple selection. The changes include enhancements to styling, functionality, and documentation for both components.
1. **Styling Updates**:
- Refactored `direction_links/component.scss` to simplify and improve the styling of direction links, adding support for all four directions (`left`, `right`, `up`, `down`) with consistent arrow icons.
2. **Storybook Integration**:
- Added a new Storybook story for direction links in `DirectionLinks.stories.js`, including variants for different directions and themes.
- Created a documentation file `DirectionLinks.mdx` to provide an overview, usage guidelines, and design resources for direction links.
3. **Component Implementation**:
- …
=> QHWT-1348 | Direction links | Update svg icons and create storybook component

src/components/internal_navigation/css/component.scss, src/components/internal_navigation/html/component.hbs, src/components/internal_navigation/js/global.js
This pull request introduces enhancements to the `internal_navigation` component, focusing on improving functionality and user experience. The changes include adding dynamic SVG icons to third-level navigation links and ensuring proper initialization of the `internalNavigation` module.
Enhancements to `internal_navigation` functionality:
* [`src/components/internal_navigation/html/component.hbs`](diffhunk://#diff-fe04bf2397f1fd7dfbf476092ea86d27f06a789dca868c3d2e9e1c37b1fda0a9L1-R1): Added a `data-path` attribute to the `qld__side-nav` element to dynamically pass the SVG path for icons.
* [`src/components/internal_navigation/js/global.js`](diffhunk://#diff-f23c10cc6c10293b7f5dd30dcb9c8cee1c892182fbe60fb38090d54b40822f44R1-R35): Implemented a script to dynamically insert SVG icons into …
=> QHWT-1375 | Side nav | Styling and svg rework

src/components/card_feature/html/component.hbs, src/components/card_multi_action/html/component.hbs, src/components/card_no_action/html/component.hbs, src/components/card_single_action/html/component.hbs, src/components/horizontal_rule/css/component.scss
[QHWT-1366](https://squizgroup.atlassian.net/browse/QHWT-1366)
This pull request introduces accessibility improvements and styling updates for horizontal rules across multiple card components. The main change is the addition of the `aria-hidden="true"` attribute to horizontal rules (`<hr>` elements) to improve screen reader behavior, along with corresponding CSS updates to ensure consistent styling.
* [`src/components/card_feature/html/component.hbs`](diffhunk://#diff-14068a92e2ce0a38779b3cbbad93af25aff2038593fb976649fb7974045fafacL70-R70): Added `aria-hidden="true"` to the `<hr>` element in the card footer to make it inaccessible to screen readers.
* [`src/components/card_multi_action/html/component.hbs`](diffhunk://#diff-80118341916a7b9c6cf5f39bca9d9045a37ec2cd63a12352866b6f8d1d042af9L13 …
=> fix/QHWT-1357-1366: Functionality update - Component - Cards require child horizontal rules to be updated

src/components/_global/css/forms/select/component.scss, src/html/component-forms.html, src/stories/SelectBox/SelectBox.stories.js
This pull request introduces updates to the styling and functionality of select components across various files, focusing on enhancements for multiple select variants, improved labeling, and consistent messaging. The most significant changes include the addition of styles for multi-select variants, updates to HTML examples for select components, and adjustments to storybook configurations for select boxes.
* [`src/components/_global/css/forms/select/component.scss`](diffhunk://#diff-fe25765d4ff9232e8cf13c87080720478fa244d6314444a21c2d6b556af6f9b6R25-R31): Added styles to remove the chevron icon for multi-select variants using the `:has` pseudo-class.
* [`src/html/component-forms.html`](diffhunk://#diff-e008546685462359407fd3ff0bdc08e6fc381353913c3b4476192bad84dc1201L61-R61): Updated …
=> QHWT-1382 | Select | Remove select chevron on multi variant

src/components/_global/css/link_columns/component.scss, src/components/internal_navigation/js/global.js, src/components/left_hand_navigation/css/component.scss
This pull request includes improvements to the styling and functionality of navigation components, with a focus on code readability, consistency, and fixing minor UI issues. The most important changes are grouped into two themes: **Styling Updates** and **JavaScript Improvements**.
* Updated padding and alignment in `src/components/_global/css/link_columns/component.scss` to prevent text from overlapping with the arrow and adjusted the arrow position for better visual alignment.
* Improved consistency in `src/components/left_hand_navigation/css/component.scss` by standardizing quotation marks in function calls, removing commented-out and redundant code, and adjusting spacing and indentation. [[1]](diffhunk://#diff-d0c3e696236f019a22141e30f63e8bc1dd63c983624153387c5111e192e3e6a9L14-L51) …
=> QHWT-1402 | Link cols, Internal nav, LHN | Patch updates for core 1.16.

src/components/updated_date/html/component.hbs
Added a `<section>` element with the class `qld__pre-footer` and a container for the "Back to top" link, improving structure .
=> Add structure for diabled last date

src/components/_global/js/tabs/global.js
[QHWT-1362](https://squizgroup.atlassian.net/browse/QHWT-1362)
This pull request refines the tab activation logic in `src/components/_global/js/tabs/global.js` to improve event handling and ensure correct element targeting. The most important changes focus on enhancing the reliability of tab activation and refining the code for better functionality.
* Updated the `clickEventListener` function to use `event.target.closest('[role="tab"]')` for determining the closest tab button, ensuring the event is triggered on the correct element.
=> fix/QHWT-1382-1362: Js Error for Tab component

src/components/code/css/component.scss, src/components/code/html/component.hbs, src/components/code/js/global.js
This pull request refactors the code component’s styling and markup to improve consistency, accessibility, and icon usage. The most significant changes are the replacement of Font Awesome icons with SVG icons, standardization of SASS mixin argument formatting, and enhancements to the component’s structure and hover/focus states.
**Icon Replacement and Markup Updates**
* Replaced all Font Awesome `<i>` icons in `component.hbs` with SVG icons using the `qld__icon` class and dynamic icon paths, improving accessibility and consistency. 
* Added a `data-path` attribute to the main code section for easier access to the core site icons path.
**SASS Mixin and Style Consistency**
* Standardized all `QLD-space` and related SASS mixin calls to use double quotes and decimal units for improved …
=> QHWT-1370 | Code | Update component icons

.storybook/assets/storybook.css, .storybook/globals.js, src/components/_global/css/forms/control_inputs/component.scss, src/html/component-forms.html, src/stories/Checkboxes/Checkboxes.js, src/stories/Checkboxes/Checkboxes.mdx, src/stories/Checkboxes/Checkboxes.stories.js, src/stories/RadioButtons/RadioButtons.js, src/stories/RadioButtons/RadioButtons.mdx, src/stories/RadioButtons/RadioButtons.stories.js, src/styles/imports/mixins.scss
This pull request introduces significant improvements to the styling and accessibility of checkbox and radio button components, as well as updates to their example usage and documentation. The changes focus on more consistent visual appearance, improved accessibility semantics, and better alignment with design guidelines.
* Refactored the checkbox and radio button styles in `component.scss` to use custom CSS for checked states, hover, and disabled states, replacing the previous use of mixins for foreground shapes. The checked state now uses border styling to create the checkmark and radio dot, resulting in more consistent and maintainable styles. [
* Improved disabled state styling for both checkboxes and radio buttons, using `$QLD-color-neutral--black__opacity-10` for background color …
=> QHWT-1361 | Checkboxes/RadioButtons | Update icons and create storybook component

src/components/breadcrumbs/js/global.js, src/components/code/js/global.js, src/components/header/js/global.js, src/components/in_page_navigation/js/global.js, src/components/internal_navigation/js/global.js
This pull request refactors several JavaScript components to improve DOM manipulation and accessibility, particularly focusing on breadcrumb, code, header, in-page navigation, and internal navigation modules. The most notable changes include replacing direct HTML string assignments with safer DOM methods, standardizing event handling and attribute usage, and improving SVG icon rendering for accessibility and maintainability.
* Replaced innerHTML assignments with `replaceChildren` and `cloneNode` in breadcrumbs and in-page navigation to prevent potential XSS issues and ensure safer DOM updates.
* Updated SVG icon rendering in breadcrumbs, code toggles, and internal navigation to use DOM methods (`createElementNS`, `appendChild`) instead of string templates, improving accessibility and …
=>  QHDEV-178 | Various components | Update vulnerable code in component global files

src/components/_global/css/cta_links/component.scss, src/components/_global/js/global.js, src/components/header/css/component.scss, src/components/header/html/component.hbs, src/components/main_navigation/html/component.hbs, src/components/main_navigation/js/global.js, src/components/mega_main_navigation/css/component.scss, src/components/mega_main_navigation/html/component.hbs, src/data/site.json
This pull request updates both the header and CTA link components to standardize icon usage, improve accessibility, and refine styling. It also refactors and modernizes utility functions in the global JavaScript file, and introduces a new method to dynamically update SVG icon paths. The most significant changes are grouped below:
**Icon Standardization and Accessibility Improvements:**
* Replaced all `<i>` icon elements with inline SVGs in `component.hbs` files for both header and main navigation, improving accessibility and consistency. 
* Updated CSS selectors in `component.scss` files to remove references to `<i>` tags and ensure proper styling for SVG icons only. 
**Styling and Layout Refinements:**
* Adjusted spacing and positioning for CTA link icons and wrappers in …
=>  QHWT-1359 | Header & Main/Mega nav | Replace FA icons

src/html/component-card_feature.html, src/html/component-card_single_action.html
Release 1.17.0 rebuild
Rebuild of https://github.com/Qld-Health-Online-Team/design-system/pull/329
=> Release 1.17.0 rebuild
